minimumReleaseAgeExclude:
  - lint-staged@17.0.8
  - '@iconify-json/lucide@1.2.116'

shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
