export default (): Promise<GamedayEvent[]> => {
  return Promise.resolve([
    {
      dateAndTime: new Date('2026-02-07T19:00:00'),
      locationName: 'Sports Hall Central',
      locationLink: 'https://maps.example.com/sports-hall-central',
      homeTeam: 'Team A',
      awayTeam: 'Team Z',
      annotations: ['Important match', 'Championship qualifier'],
      helperAdmission: 'John Doe',
      helpingTeam: 'Team B',
      helperSteward: 'Bob Johnson',
      helperTimekeeper: 'Alice Brown',
      helperSecretary: 'Charlie Davis',
      helperWipe: 'Diana Wilson',
    },
    {
      dateAndTime: new Date('2026-02-14T18:30:00'),
      locationName: 'East Arena',
      locationLink: 'https://maps.example.com/east-arena',
      homeTeam: 'Team B',
      awayTeam: 'Team Y',
      annotations: ['Friendly match'],
      helperAdmission: 'Eve Martinez',
      helpingTeam: 'Team C',
      helperSteward: 'Grace Lee',
      helperTimekeeper: 'Henry Taylor',
      helperSecretary: 'Iris Anderson',
      helperWipe: 'Jack Thomas',
    },
    {
      dateAndTime: new Date('2026-02-21T20:00:00'),
      locationName: 'West Court',
      locationLink: 'https://maps.example.com/west-court',
      homeTeam: 'Team C',
      awayTeam: 'Team X',
      annotations: ['Division final'],
      helperAdmission: 'Karen White',
      helpingTeam: 'Team A',
      helperSteward: 'Mona Robinson',
      helperTimekeeper: 'Nathan Clark',
      helperSecretary: 'Olivia Lewis',
      helperWipe: 'Peter Walker',
    },
    {
      dateAndTime: new Date('2026-02-28T19:30:00'),
      locationName: 'North Gym',
      locationLink: 'https://maps.example.com/north-gym',
      homeTeam: 'Team D',
      awayTeam: 'Team W',
      annotations: ['Regular match'],
      helperAdmission: 'Quinn Martinez',
      helpingTeam: 'Team E',
      helperSteward: 'Rachel Green',
      helperTimekeeper: 'Samuel Johnson',
      helperSecretary: 'Tina Harris',
      helperWipe: 'Uma Patel',
    },
    {
      dateAndTime: new Date('2026-03-07T18:00:00'),
      locationName: 'South Stadium',
      locationLink: 'https://maps.example.com/south-stadium',
      homeTeam: 'Team E',
      awayTeam: 'Team V',
      annotations: ['Youth championship', 'High priority'],
      helperAdmission: 'Victor Young',
      helpingTeam: 'Team F',
      helperSteward: 'Wendy King',
      helperTimekeeper: 'Xavier Scott',
      helperSecretary: 'Yara Ahmed',
      helperWipe: 'Zoe Bennett',
    },
    {
      dateAndTime: new Date('2026-03-14T19:45:00'),
      locationName: 'Central Hall',
      locationLink: 'https://maps.example.com/central-hall',
      homeTeam: 'Team F',
      awayTeam: 'Team V',
      annotations: ['Friendly match', 'Exhibition'],
      helperAdmission: 'Adam Cooper',
      helpingTeam: 'Team G',
      helperSteward: 'Bella Morgan',
      helperTimekeeper: 'Carlos Ruiz',
      helperSecretary: 'Diana Foster',
      helperWipe: 'Ethan Cross',
    },
    {
      dateAndTime: new Date('2026-03-21T20:15:00'),
      locationName: 'East Athletic Complex',
      locationLink: 'https://maps.example.com/east-athletic',
      homeTeam: 'Team G',
      awayTeam: 'Team H',
      annotations: ['League match'],
      helperAdmission: 'Fiona Blake',
      helpingTeam: 'Team H',
      helperSteward: 'George Stone',
      helperTimekeeper: 'Hannah Price',
      helperSecretary: 'Isaac Bennett',
      helperWipe: 'Julia Morris',
    },
    {
      dateAndTime: new Date('2026-03-28T17:30:00'),
      locationName: 'West Premier Arena',
      locationLink: 'https://maps.example.com/west-premier',
      homeTeam: 'Team H',
      awayTeam: 'Team U',
      annotations: ['Semi-final', 'Important match'],
      helperAdmission: 'Kevin Murphy',
      helpingTeam: 'Team I',
      helperSteward: 'Lara Rogers',
      helperTimekeeper: 'Marcus Boyd',
      helperSecretary: 'Nina Palmer',
      helperWipe: 'Oscar Graham',
    },
    {
      dateAndTime: new Date('2026-04-04T19:00:00'),
      locationName: 'North Training Center',
      locationLink: 'https://maps.example.com/north-training',
      homeTeam: 'Team I',
      awayTeam: 'Team T',
      annotations: ['Regular season'],
      helperAdmission: 'Pam Stewart',
      helpingTeam: 'Team J',
      helperSteward: 'Quinn Evans',
      helperTimekeeper: 'Rita Collins',
      helperSecretary: 'Sean Sanchez',
      helperWipe: 'Tasha Hughes',
    },
    {
      dateAndTime: new Date('2026-04-11T18:45:00'),
      locationName: 'South Convention Center',
      locationLink: 'https://maps.example.com/south-convention',
      homeTeam: 'Team J',
      awayTeam: 'Team S',
      annotations: ['Conference match', 'Away game'],
      helperAdmission: 'Ulysses Cooper',
      helpingTeam: 'Team A',
      helperSteward: 'Vanessa Parker',
      helperTimekeeper: 'Wayne Simpson',
      helperSecretary: 'Xena Long',
      helperWipe: 'Yuri Bell',
    },
    {
      dateAndTime: new Date('2026-04-18T20:00:00'),
      locationName: 'Central Sports Complex',
      locationLink: 'https://maps.example.com/central-sports',
      homeTeam: 'Team A',
      awayTeam: 'Team R',
      annotations: ['Final match', 'Championship contender'],
      helperAdmission: 'Zara Cox',
      helpingTeam: 'Team D',
      helperSteward: 'Andrew Kennedy',
      helperTimekeeper: 'Brenda Warren',
      helperSecretary: 'Carl Grant',
      helperWipe: 'Donna Harper',
    },
    {
      dateAndTime: new Date('2026-04-25T19:15:00'),
      locationName: 'East Recreation Hall',
      locationLink: 'https://maps.example.com/east-recreation',
      homeTeam: 'Team B',
      awayTeam: 'Team Q',
      annotations: ['Playoff round'],
      helperAdmission: 'Evan Ross',
      helpingTeam: 'Team E',
      helperSteward: 'Faye Carter',
      helperTimekeeper: 'Gary Hart',
      helperSecretary: 'Helen Perry',
      helperWipe: 'Igor Spencer',
    },
  ]);
}


type GamedayEvent = {
  dateAndTime: Date;
  locationName: string;
  locationLink: string;
  homeTeam: string;
  awayTeam: string;
  annotations: string[];
  helpingTeam: string;
  helperAdmission: string;
  helperSteward: string;
  helperTimekeeper: string;
  helperSecretary: string;
  helperWipe: string;
}