name: Test against Deno Deploy

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Get Deno Deploy URL
        id: get-url
        env:
          DENO_PROJECT_NAME: ${{ secrets.DENO_PROJECT_NAME }}
          DENO_ORG_NAME: ${{ secrets.DENO_ORG_NAME }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          # fix the branch name to be cut to max 25 characters and replace slashes with dashes
          # also if the 25th character is a dash, cut it to 26 characters to avoid ending with a dash
          # also convert to lowercase
          TRIMMED="${BRANCH_NAME:0:25}"
          if [[ "${TRIMMED: -1}" == "-" ]]; then
            BRANCH_NAME="${BRANCH_NAME:0:26}"
          else
            BRANCH_NAME="${BRANCH_NAME:0:25}"
          fi
          BRANCH_NAME=$(echo "${BRANCH_NAME}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          URL="https://${DENO_PROJECT_NAME}--${BRANCH_NAME}.${DENO_ORG_NAME}.deno.net"
          echo "TEST_HOST=$URL" >> $GITHUB_ENV
          echo "deployment_url=$URL" >> $GITHUB_OUTPUT

      - name: Run Vitest tests
        run: pnpm test
        env:
          TEST_HOST: ${{ env.TEST_HOST }}

      - name: Run Accessibility tests
        run: pnpm test:a11y
        env:
          TEST_HOST: ${{ env.TEST_HOST }}
